### PR TITLE
CDA-446 fix sonar qube config

### PR DESCRIPTION
**Pull request by Sul-Aga-kainos**
## Description

Related issue: [CDA-446](https://dvsa.atlassian.net/browse/CDA-446)

## Before submitting (or marking as "ready for review")

- [*] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [*] Have you performed a self-review of the code
- [] Have you have added tests that prove the fix or feature is effective and working
- [*] Did you make sure to update any documentation relating to this change?

### CODE REVIEW

**Review by Ian-Hodges — COMMENTED** [review]
Have you tested it runs successfully in the pipeline?

**Comment by Sul-Aga-kainos** [comment]
> 

How can I do that?

**Comment by Sul-Aga-kainos** [comment]
> Have you tested it runs successfully in the pipeline?

How can I do that? I did ran sonar qube locally along with unit tests and linting

**Comment by Ian-Hodges** [comment]
> > Have you tested it runs successfully in the pipeline?
> 
> How can I do that? I did ran sonar qube locally along with unit tests and linting

You'll need to create a new feature environment and run the build job for it. I'll message you with details.

**Review by Ian-Hodges — APPROVED** [review]

**Review by kpearmanbjss — APPROVED** [review]

**Pull request merged**
